#!/bin/sh

if [ -e /etc/httpd/conf.d/wpad.conf ]; then
    logger -p local6.notice -t installer "app-wpad-core - disabling WPAD apache configlet on un-install"
    rm -rf /etc/httpd/conf.d/wpad.conf
    sudo /usr/bin/systemctl condrestart httpd
fi
