#!/usr/clearos/sandbox/usr/bin/php
<?php

/**
 * WPAD Init Script.
 *
 * @category   apps
 * @package    wpad
 * @subpackage scripts
 * @author     ClearFoundation <developer@clearfoundation.com>
 * @copyright  2018 ClearFoundation
 * @license    http://www.gnu.org/copyleft/gpl.html GNU General Public License version 3 or later
 * @link       http://www.clearfoundation.com/docs/developer/apps/wpad/
 */

///////////////////////////////////////////////////////////////////////////////
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////
// B O O T S T R A P
///////////////////////////////////////////////////////////////////////////////

$bootstrap = getenv('CLEAROS_BOOTSTRAP') ? getenv('CLEAROS_BOOTSTRAP') : '/usr/clearos/framework/shared';
require_once $bootstrap . '/bootstrap.php';

///////////////////////////////////////////////////////////////////////////////
// T R A N S L A T I O N S
///////////////////////////////////////////////////////////////////////////////

clearos_load_language('base');
clearos_load_language('wpad');

///////////////////////////////////////////////////////////////////////////////
// D E P E N D E N C I E S
///////////////////////////////////////////////////////////////////////////////

// Classes
//--------

use \clearos\apps\wpad\Wpad as Wpad;

clearos_load_library('wpad/Wpad');
clearos_load_library('base/File');
clearos_load_library('base/Script');
clearos_load_library('users/User_Factory');

// Exceptions
//-----------

use \Exception as Exception;

///////////////////////////////////////////////////////////////////////////////
// M A I N
///////////////////////////////////////////////////////////////////////////////

//--------------------------------------------------------------------
// Command line options
//--------------------------------------------------------------------

$short_options  = '';

// Common
$short_options .= 'h';   // Help

$helpopts  = '
  -h: help
';

// Handle command line options
//----------------------------

$options = getopt($short_options);

$wpad = new Wpad();

$help = isset($options['h']) ? TRUE : FALSE;

if ($help) {
    echo "Used to re-initialize WPAD service on ClearOS.\n";
    echo $helpopts;
    exit(0);
}

try {
    $wpad->auto_generate_pac();
    echo "OK\n";
} catch (Exception $e) {
    echo "Error occurred:  " . clearos_exception_message($e) . "\n";
}

// vim: syntax=php
